[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x2162c916e897c6cfa038fade1c8dff9870c815a41358ae69f5523cbf82c0a27f'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]